DROP TABLE IF EXISTS CUSTOMER2;
CREATE TABLE IF NOT EXISTS CUSTOMER2 (
CUSTOMER_ID   INT,
CUSTOMER_NAME STRING,
GENDER        INT,
AGE           INT,
ADDRESS       STRING,
JOB_ID        INT)
ROW FORMAT DELIMITED FIELDS TERMINATED BY ','
STORED AS TEXTFILE;
