DROP TABLE IF EXISTS SALES_DETAIL;
DROP TABLE IF EXISTS SALES_TRAN;
DROP TABLE IF EXISTS CUSTOMER;
DROP TABLE IF EXISTS STAFF;
DROP TABLE IF EXISTS BRANCH;
DROP TABLE IF EXISTS STOCK_PRODUCT;
DROP TABLE IF EXISTS PRODUCT;
DROP TABLE IF EXISTS PRODUCT_TYPE;

CREATE TABLE IF NOT EXISTS PRODUCT_TYPE (
PRODUCT_TYPE_ID   INT,   -- 商品分類ID
PRODUCT_TYPE_NAME STRING -- 商品分類名
)
ROW FORMAT DELIMITED FIELDS TERMINATED BY ','
STORED AS TEXTFILE;

CREATE TABLE IF NOT EXISTS PRODUCT (
PRODUCT_ID      INT,    -- 商品ID
PRODUCT_TYPE_ID INT,    -- 商品分類ID
PRODUCT_NAME    STRING, -- 商品名
PRICE           INT     -- 商品価格
)
ROW FORMAT DELIMITED FIELDS TERMINATED BY ','
STORED AS TEXTFILE;

CREATE TABLE IF NOT EXISTS STOCK_PRODUCT (
PRODUCT_ID INT, -- 商品ID
QUANTITY   INT  -- 残り個数
)
ROW FORMAT DELIMITED FIELDS TERMINATED BY ','
STORED AS TEXTFILE;

CREATE TABLE IF NOT EXISTS BRANCH (
BRANCH_ID   INT,   -- 支店ID
BRANCH_NAME STRING -- 支店名
)
ROW FORMAT DELIMITED FIELDS TERMINATED BY ','
STORED AS TEXTFILE;

CREATE TABLE IF NOT EXISTS STAFF (
STAFF_ID   INT,    -- 社員ID
STAFF_NAME STRING, -- 社員名
BRANCH_ID  INT     -- 支店ID
)
ROW FORMAT DELIMITED FIELDS TERMINATED BY ','
STORED AS TEXTFILE;

CREATE TABLE IF NOT EXISTS CUSTOMER (
BRANCH_ID     INT,    -- 支店ID
CUSTOMER_ID   INT,    -- 取引先ID
CUSTOMER_NAME STRING, -- 取引先名
EMAIL_ADDRESS STRING, -- 電子メールアドレス
POSTAL_CODE   STRING, -- 郵便ID
ADDRESS1      STRING, -- 住所1
ADDRESS2      STRING  -- 住所2
)
ROW FORMAT DELIMITED FIELDS TERMINATED BY ','
STORED AS TEXTFILE;

CREATE TABLE IF NOT EXISTS SALES_TRAN (
SALES_ID          INT,    -- 売上ID
SALES_DATE        STRING, -- 売上日付
DUE_DATE          STRING, -- 支払期日
BRANCH_ID         INT,    -- 支店ID
CUSTOMER_ID       INT,    -- 取引先ID
STAFF_IN_CHARGE   INT,    -- 担当者の社員ID
UPDATE_STOCK_FLAG INT     -- 在庫テーブル更新フラグ
)
ROW FORMAT DELIMITED FIELDS TERMINATED BY ','
STORED AS TEXTFILE;

CREATE TABLE SALES_DETAIL (
SALES_ID        INT, -- 売上ID
SALES_DETAIL_ID INT, -- 売上詳細ID
PRODUCT_ID      INT, -- 商品ID
PRODUCT_PRICE   INT, -- 商品価格
SALES_COUNT     INT  -- 個数
)
ROW FORMAT DELIMITED FIELDS TERMINATED BY ','
STORED AS TEXTFILE;
