TRUNCATE TABLE HISTORICAL_SALES_BY_PRODUCT;
INSERT INTO HISTORICAL_SALES_BY_PRODUCT
SELECT SD.PRODUCT_ID, DATE_FORMAT(ST.SALES_DATE,'%Y%m'), COUNT(*)
FROM SALES_TRAN ST INNER JOIN SALES_DETAIL SD
ON ST.SALES_ID = SD.SALES_ID
GROUP BY SD.PRODUCT_ID, DATE_FORMAT(ST.SALES_DATE,'%Y%m')
